# Generated by Django 6.0.1 on 2026-02-17 00:23

import apps.productos.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Breve descripción de los productos en esta categoría', null=True, verbose_name='Descripción')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='categorias/', verbose_name='Imagen')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('orden', models.IntegerField(blank=True, default=0, help_text='Orden de aparición en el catálogo', null=True, verbose_name='Orden')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio de venta')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen principal')),
                ('peso_gramos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Peso (gramos)')),
                ('tiempo_impresion_horas', models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado de impresión', max_digits=8, verbose_name='Tiempo de impresión (horas)')),
                ('mostrar_en_web', models.BooleanField(default=False, verbose_name='Mostrar en web')),
                ('destacado', models.BooleanField(default=False, help_text='Aparecerá en la página principal', verbose_name='Destacado')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('categoria', models.ForeignKey(default=apps.productos.models.get_default_categoria, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='productos', to='productos.categoria', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto/Pieza',
                'verbose_name_plural': 'Productos/Piezas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ImagenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/galeria/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden en que aparecerán las fotos', verbose_name='Orden')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripción')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen de Producto',
                'verbose_name_plural': 'Galería de Imágenes',
                'ordering': ['producto', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='VarianteMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_usados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
            ],
            options={
                'verbose_name': 'Detalle de Material de Variante',
            },
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_disponible', models.IntegerField(default=0, verbose_name='Stock disponible')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, help_text='Sobreprecio respecto al precio base', max_digits=10, verbose_name='Precio adicional')),
                ('codigo_sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('firma_materiales', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('materiales_consumidos', models.ManyToManyField(related_name='variantes_que_lo_usan', through='productos.VarianteMaterialDetalle', to='materiales.material')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto',
                'verbose_name_plural': 'Variantes de Productos',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.AddField(
            model_name='variantematerialdetalle',
            name='variante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_material', to='productos.varianteproducto'),
        ),
        migrations.CreateModel(
            name='ProduccionInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_producida', models.PositiveIntegerField(help_text='Cantidad de piezas impresas para stock', verbose_name='Cantidad producida')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='productos.varianteproducto', verbose_name='Variante')),
            ],
            options={
                'verbose_name': 'Producción Interna',
                'verbose_name_plural': 'Producciones Internas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'firma_materiales'), name='unique_variante_por_producto'),
        ),
        migrations.AlterUniqueTogether(
            name='variantematerialdetalle',
            unique_together={('variante', 'material')},
        ),
    ]
