# Generated by Django 6.0.1 on 2026-02-19 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='peso_gramos',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tiempo_impresion_horas',
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='es_default',
            field=models.BooleanField(default=False, verbose_name='Variante principal'),
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='tiempo_impresion_horas',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tiempo estimado de impresión', max_digits=8, verbose_name='Tiempo de impresión (horas)'),
        ),
    ]
