# Generated by Django 6.0.1 on 2026-02-10 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_color_unique_color_nombre_case_insensitive_and_more'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VarianteMaterialDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_usados', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_material', to='productos.varianteproducto')),
            ],
            options={
                'verbose_name': 'Detalle de Material de Variante',
                'unique_together': {('variante', 'material')},
            },
        ),
        migrations.AddField(
            model_name='varianteproducto',
            name='materiales_consumidos',
            field=models.ManyToManyField(related_name='variantes_que_lo_usan', through='productos.VarianteMaterialDetalle', to='materiales.material'),
        ),
    ]
