# Generated by Django 6.0.1 on 2026-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_variantematerialdetalle_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='varianteproducto',
            options={'ordering': ['producto__nombre'], 'verbose_name': 'Variante de Producto', 'verbose_name_plural': 'Variantes de Productos'},
        ),
        migrations.AlterUniqueTogether(
            name='varianteproducto',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='produccioninterna',
            name='gramos_por_pieza',
        ),
        migrations.RemoveField(
            model_name='produccioninterna',
            name='material',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='material_base',
        ),
        migrations.AlterField(
            model_name='varianteproducto',
            name='precio_adicional',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Sobreprecio respecto al precio base', max_digits=10, verbose_name='Precio adicional'),
        ),
        migrations.RemoveField(
            model_name='varianteproducto',
            name='material',
        ),
    ]
