# Generated by Django 6.0.1 on 2026-02-11 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_varianteproducto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='orden',
            field=models.IntegerField(blank=True, default=0, help_text='Orden de aparición en el catálogo', null=True, verbose_name='Orden'),
        ),
    ]
