# Generated by Django 6.0.1 on 2026-02-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0005_material_enlace_compra'),
        ('productos', '0004_alter_categoria_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='varianteproducto',
            name='firma_materiales',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='varianteproducto',
            constraint=models.UniqueConstraint(fields=('producto', 'firma_materiales'), name='unique_variante_por_producto'),
        ),
    ]
