# Generated by Django 6.0.1 on 2026-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActualizacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('imagen', models.ImageField(blank=True, help_text='Foto del progreso', null=True, upload_to='pedidos/actualizaciones/', verbose_name='Imagen')),
                ('visible_cliente', models.BooleanField(default=True, help_text='¿El cliente puede ver esta actualización?', verbose_name='Visible para cliente')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Actualización de Pedido',
                'verbose_name_plural': 'Actualizaciones de Pedidos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción del ítem (para productos personalizados)', max_length=300, null=True, verbose_name='Descripción/Nombre de pieza')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Precio unitario')),
                ('gramos_por_unidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Gramos por unidad')),
                ('costo_material_unitario', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Ítem de Pedido',
                'verbose_name_plural': 'Ítems de Pedido',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('metodo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia bancaria'), ('Tarjeta', 'Tarjeta de crédito/débito'), ('PayPal', 'PayPal'), ('Otro', 'Otro')], max_length=20, verbose_name='Método de pago')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia, transacción, etc.', max_length=200, verbose_name='Referencia')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes/', verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del pedido', verbose_name='Descripción')),
                ('peso_estimado_g', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Peso estimado (gramos)')),
                ('tiempo_estimado_h', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiempo estimado (horas)')),
                ('precio_kwh_usado', models.DecimalField(decimal_places=2, default=15.0, help_text='Costo de energía por kWh', max_digits=10, verbose_name='Precio kWh')),
                ('costo_material', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de material')),
                ('costo_energia', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Costo de energía')),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, help_text='Costos adicionales (envío, acabados, etc.)', max_digits=12, verbose_name='Otros costos')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio total')),
                ('estado_pedido', models.CharField(choices=[('En_Espera', 'En espera de pago'), ('Confirmado', 'Confirmado - Pendiente de producción'), ('En_Produccion', 'En producción'), ('Listo', 'Listo para entrega'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='En_Espera', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_inicio_produccion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha inicio producción')),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(help_text='Descripción del producto a cotizar', verbose_name='Descripción')),
                ('imagen_referencia', models.ImageField(blank=True, null=True, upload_to='pedidos/referencias/', verbose_name='Imagen de referencia')),
                ('enlace_referencia', models.URLField(blank=True, help_text='Link a un modelo 3D o referencia', null=True, verbose_name='Enlace de referencia')),
                ('dimensiones_aprox', models.CharField(blank=True, help_text='Ej: 10x10x5 cm', max_length=100, verbose_name='Dimensiones aproximadas')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Cotizada', 'Cotización enviada'), ('Aceptada', 'Aceptada por cliente'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('precio_cotizado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio cotizado')),
                ('tiempo_estimado', models.CharField(blank=True, help_text='Ej: 2-3 días hábiles', max_length=100, verbose_name='Tiempo estimado')),
                ('notas_admin', models.TextField(blank=True, verbose_name='Notas del administrador')),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de respuesta')),
            ],
            options={
                'verbose_name': 'Solicitud de Cotización',
                'verbose_name_plural': 'Solicitudes de Cotización',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
