# Generated by Django 6.0.1 on 2026-02-12 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Impresora')),
                ('modelo', models.CharField(help_text='Ej: Ender 3, Artillery X2', max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Imprimiendo', 'Imprimiendo'), ('Mantenimiento', 'En Mantenimiento')], default='Disponible', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='itempedido',
            name='impresora_asignada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_asignados', to='pedidos.impresora', verbose_name='Impresora'),
        ),
    ]
