# Generated by Django 6.0.1 on 2026-02-13 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_alter_color_codigo_hex'),
        ('pedidos', '0003_impresora_itempedido_impresora_asignada'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='costo_material_unitario',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='material_personalizado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiales.material', verbose_name='Material utilizado'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='descripcion',
            field=models.CharField(help_text='Descripción del ítem (para productos personalizados)', max_length=300, verbose_name='Descripción/Nombre de pieza'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio unitario'),
        ),
    ]
