# Generated by Django 6.0.1 on 2026-02-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_stock_descontado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('En_Espera', 'En espera de pago'), ('Confirmado', 'Confirmado - Pendiente de producción'), ('En_Produccion', 'En producción'), ('Listo', 'Listo para entrega'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Fallido', 'Error de Impresión / Desperdicio')], default='En_Espera', max_length=20, verbose_name='Estado'),
        ),
    ]
