# Generated by Django 6.0.1 on 2026-02-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_itempedido_costo_material_unitario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripción del ítem (para productos personalizados)', max_length=300, null=True, verbose_name='Descripción/Nombre de pieza'),
        ),
    ]
