# Generated by Django 6.0.1 on 2026-02-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_notapedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='peso_estimado_g',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Peso estimado (gramos)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='precio_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tiempo_estimado_h',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tiempo estimado (horas)'),
        ),
    ]
