# Generated by Django 6.0.1 on 2026-02-20 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_alter_pedido_peso_estimado_g_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='guest_ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad (Invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_direccion',
            field=models.TextField(blank=True, verbose_name='Dirección (Invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email (Invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_nombre',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre (Invitado)'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='guest_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono (Invitado)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
    ]
