# Generated by Django 6.0.1 on 2026-02-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_pedido_guest_ciudad_pedido_guest_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Contra_entrega', 'Contra entrega'), ('Transferencia', 'Transferencia bancaria'), ('Tarjeta', 'Tarjeta de crédito/débito'), ('PayPal', 'PayPal'), ('Otro', 'Otro')], max_length=20, verbose_name='Método de pago'),
        ),
    ]
