# Generated by Django 6.0.1 on 2026-02-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0008_alter_pago_metodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='imagen_referencia',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pedidos/referencias/', verbose_name='Imagen de referencia'),
        ),
    ]
