# Generated by Django 6.0.1 on 2026-02-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0009_alter_solicitudcotizacion_imagen_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100, verbose_name='Nombre del banco')),
                ('titular', models.CharField(max_length=200, verbose_name='Titular de la cuenta')),
                ('numero_cuenta', models.CharField(max_length=50, verbose_name='Número de cuenta')),
                ('tipo_cuenta', models.CharField(blank=True, help_text='Ej: Ahorro, Corriente', max_length=50, verbose_name='Tipo de cuenta')),
                ('cedula', models.CharField(blank=True, max_length=20, verbose_name='Cédula del titular')),
                ('telefono_pago', models.CharField(blank=True, max_length=20, verbose_name='Teléfono para pagos móviles')),
                ('instrucciones_adicionales', models.TextField(blank=True, help_text='Texto extra que verá el cliente al seleccionar transferencia', verbose_name='Instrucciones adicionales')),
                ('porcentaje_anticipo', models.DecimalField(decimal_places=2, default=50.0, help_text='Porcentaje del total que se pide como pago inicial (ej: 50)', max_digits=5, verbose_name='% de anticipo para pedidos personalizados')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuración de Pagos',
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_cliente',
            field=models.ImageField(blank=True, null=True, upload_to='pagos/comprobantes_cliente/', verbose_name='Comprobante del cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='comprobante_estado',
            field=models.CharField(blank=True, choices=[('Pendiente', 'Pendiente de revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], max_length=20, verbose_name='Estado del comprobante'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago_preferido',
            field=models.CharField(blank=True, choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia bancaria'), ('Contraentrega', 'Pago contraentrega')], max_length=20, verbose_name='Método de pago preferido'),
        ),
    ]
