# Generated by Django 6.0.1 on 2026-02-25 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_initial'),
        ('pedidos', '0010_configuracionpago_pedido_comprobante_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado_pedido',
            field=models.CharField(choices=[('En_Espera', 'En espera de pago'), ('Confirmado', 'Confirmado - Pendiente de producción'), ('En_Produccion', 'En producción'), ('Listo', 'Listo para entrega'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='En_Espera', max_length=20, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='PerdidaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_perdidos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gramos perdidos')),
                ('motivo', models.TextField(blank=True, help_text='Ej: Adhesión fallida a la mitad de la impresión, fallo de filamento, etc.', verbose_name='Motivo / descripción del fallo')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.material', verbose_name='Material perdido')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdidas_material', to='pedidos.pedido', verbose_name='Pedido')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pérdida de Material',
                'verbose_name_plural': 'Pérdidas de Material',
                'ordering': ['-fecha'],
            },
        ),
    ]
