# Generated by Django 6.0.1 on 2026-03-03 21:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0011_alter_pedido_estado_pedido_perdidamaterial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='imagen_referencia',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='pedidos/referencias/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'svg'])], verbose_name='Imagen de referencia'),
        ),
    ]
