# Generated by Django 6.0.1 on 2026-03-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0013_alter_solicitudcotizacion_imagen_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcotizacion',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente de revisión'), ('Revisada', 'Revisada — en proceso'), ('Completada', 'Convertida a pedido'), ('Rechazada', 'Rechazada')], default='Pendiente', max_length=15, verbose_name='Estado'),
        ),
    ]
