# Generated by Django 6.0.1 on 2026-03-10 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0015_alter_solicitudcotizacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='item_padre',
            field=models.ForeignKey(blank=True, help_text='Si está asignado, este ítem es un componente de producción del ítem padre.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='pedidos.itempedido', verbose_name='Ítem contenedor'),
        ),
    ]
