# Generated by Django 6.0.1 on 2026-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0016_itempedido_item_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='fallo_registrado',
            field=models.BooleanField(default=False, help_text='True si este ítem/componente tuvo un fallo de impresión confirmado. El stock de su material NO se devuelve al revertir el pedido.', verbose_name='Fallo registrado'),
        ),
    ]
