# Generated by Django 6.0.1 on 2026-03-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0017_itempedido_fallo_registrado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='fecha_respuesta',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='notas_admin',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='precio_cotizado',
        ),
        migrations.RemoveField(
            model_name='solicitudcotizacion',
            name='tiempo_estimado',
        ),
    ]
