# Generated by Django 6.0.1 on 2026-03-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0018_remove_solicitudcotizacion_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='costo_energia',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='precio_kwh_usado',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tiempo_estimado_h',
        ),
    ]
