# Generated by Django 6.0.1 on 2026-03-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0019_remove_pedido_costo_energia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notapedido',
            name='tipo',
            field=models.CharField(choices=[('manual', 'Manual'), ('otros_costos', 'Otros Costos'), ('fallo', 'Fallo de Impresión'), ('sistema', 'Sistema')], default='manual', max_length=20, verbose_name='Tipo de nota'),
        ),
    ]
