# Generated by Django 6.0.1 on 2026-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Impresora')),
                ('modelo', models.CharField(help_text='Ej: Ender 3, Artillery X2', max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Imprimiendo', 'Imprimiendo'), ('Mantenimiento', 'En Mantenimiento'), ('Offline', 'Fuera de Servicio')], default='Disponible', max_length=20)),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
            },
        ),
    ]
