# Generated by Django 6.0.1 on 2026-02-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Impresora'),
        ),
    ]
