# Generated by Django 6.0.1 on 2026-02-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_impresora_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titulo_normal', models.CharField(default='Tus ideas en', max_length=80, verbose_name='Título del hero (parte normal)')),
                ('hero_titulo_destacado', models.CharField(default='3D', max_length=40, verbose_name='Título del hero (parte destacada en verde)')),
                ('hero_subtitulo', models.TextField(default='Desde prototipos industriales hasta figuras de colección. Calidad garantizada en cada capa.', verbose_name='Subtítulo del hero')),
                ('hero_boton_primario', models.CharField(default='Empezar mi proyecto', max_length=60, verbose_name='Texto botón primario (no autenticado)')),
                ('stat_piezas_numero', models.PositiveIntegerField(default=50, verbose_name='Número: piezas producidas')),
                ('stat_piezas_etiqueta', models.CharField(default='Piezas Producidas', max_length=40, verbose_name='Etiqueta: piezas producidas')),
                ('stat_respuesta_numero', models.CharField(default='24h', max_length=20, verbose_name='Número: tiempo de respuesta')),
                ('stat_respuesta_etiqueta', models.CharField(default='Respuesta Rápida', max_length=40, verbose_name='Etiqueta: tiempo de respuesta')),
                ('stat_materiales_numero', models.CharField(default='8+', max_length=20, verbose_name='Número: tipos de material')),
                ('stat_materiales_etiqueta', models.CharField(default='Tipos de Material', max_length=40, verbose_name='Etiqueta: tipos de material')),
                ('stat_garantia_numero', models.CharField(default='100%', max_length=20, verbose_name='Número: garantía')),
                ('stat_garantia_etiqueta', models.CharField(default='Garantía de Calidad', max_length=40, verbose_name='Etiqueta: garantía')),
                ('mostrar_seccion_materiales_index', models.BooleanField(default=True, verbose_name='Mostrar sección de materiales en el Inicio')),
                ('materiales_titulo', models.CharField(default='Materiales de Grado Profesional', max_length=80, verbose_name='Título sección materiales')),
                ('materiales_subtitulo', models.CharField(default='Seleccionamos la mejor materia prima para garantizar la durabilidad de tus piezas.', max_length=200, verbose_name='Subtítulo sección materiales')),
                ('mostrar_seccion_productos_destacados', models.BooleanField(default=True, verbose_name="Mostrar sección 'Lo más pedido'")),
                ('productos_destacados_titulo', models.CharField(default='Lo más pedido', max_length=80, verbose_name='Título sección productos destacados')),
                ('productos_destacados_subtitulo', models.CharField(default='Nuestras piezas favoritas del catálogo.', max_length=200, verbose_name='Subtítulo sección productos destacados')),
                ('max_productos_destacados', models.PositiveSmallIntegerField(default=4, verbose_name='Máx. productos a mostrar (1–8)')),
                ('mostrar_cta_final', models.BooleanField(default=True, verbose_name='Mostrar banner CTA final')),
                ('cta_titulo', models.CharField(default='¿Listo para materializar tu idea?', max_length=100, verbose_name='Título del CTA')),
                ('cta_subtitulo', models.CharField(default='Únete a nuestra plataforma, sube tu archivo STL y recibe una cotización personalizada hoy mismo.', max_length=300, verbose_name='Subtítulo del CTA')),
                ('cta_boton', models.CharField(default='Registrarme Gratis', max_length=60, verbose_name='Texto botón del CTA')),
                ('proceso_titulo', models.CharField(default='Proceso de Realización', max_length=80, verbose_name='Título de la página Proceso')),
                ('proceso_subtitulo', models.CharField(default='Desde una simple idea o un archivo profesional hasta la pieza en tus manos.', max_length=200, verbose_name='Subtítulo de la página Proceso')),
                ('proceso_cta_titulo', models.CharField(default='¿Tienes un archivo listo o una idea en mente?', max_length=100, verbose_name='Título CTA al final de Proceso')),
                ('proceso_cta_boton', models.CharField(default='Subir mi Archivo / Idea', max_length=60, verbose_name='Texto botón CTA de Proceso')),
                ('whatsapp_numero', models.CharField(blank=True, default='', max_length=20, verbose_name='Número WhatsApp (formato: 18095551234)')),
                ('mostrar_boton_whatsapp', models.BooleanField(default=False, verbose_name='Mostrar botón flotante de WhatsApp')),
                ('email_contacto', models.EmailField(blank=True, default='info@3dprint.do', max_length=254, verbose_name='Email de contacto (footer)')),
                ('ciudad_contacto', models.CharField(blank=True, default='Santo Domingo, RD', max_length=80, verbose_name='Ciudad (footer)')),
            ],
            options={
                'verbose_name': 'Configuración del Sitio',
                'verbose_name_plural': 'Configuración del Sitio',
            },
        ),
    ]
