# Generated by Django 6.0.1 on 2026-02-22 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_configuracionsitio'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardPublica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(choices=[('materiales', 'Materiales (Inicio)'), ('proceso', 'Pasos del Proceso')], max_length=20, verbose_name='Sección')),
                ('orden', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Visible')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción / Contenido')),
                ('badge_texto', models.CharField(blank=True, default='', max_length=40, verbose_name='Texto del badge (ej: Estético)')),
                ('badge_color', models.CharField(choices=[('gray', 'Gris (default)'), ('green', 'Verde'), ('purple', 'Morado'), ('blue', 'Azul'), ('red', 'Rojo'), ('yellow', 'Amarillo')], default='gray', max_length=10, verbose_name='Color del badge')),
                ('tags', models.CharField(blank=True, default='', help_text='Ej: Fácil de Pintar, Eco-Friendly', max_length=200, verbose_name='Tags separados por coma')),
                ('paso_numero', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número del paso (solo Proceso)')),
                ('es_paso_destacado', models.BooleanField(default=False, verbose_name='Paso destacado (verde, solo Proceso)')),
            ],
            options={
                'verbose_name': 'Card Pública',
                'verbose_name_plural': 'Cards Públicas',
                'ordering': ['seccion', 'orden'],
            },
        ),
    ]
