# Generated by Django 6.0.1 on 2026-02-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cardpublica'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpublica',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Recomendado: 400x300px para mejor visualización', null=True, upload_to='cards/', verbose_name='Imagen del card'),
        ),
    ]
