# Generated by Django 6.0.1 on 2026-02-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cardpublica_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpublica',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Recomendado: 400x300px para mejor visualización', max_length=255, null=True, upload_to='cards/', verbose_name='Imagen del card'),
        ),
    ]
