# Generated by Django 6.0.1 on 2026-02-24 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cardpublica_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='cta_boton',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='cta_subtitulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='cta_titulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='hero_boton_primario',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='hero_subtitulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='hero_titulo_destacado',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='hero_titulo_normal',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='materiales_subtitulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='materiales_titulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='mostrar_cta_final',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='mostrar_seccion_materiales_index',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='proceso_cta_boton',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='proceso_cta_titulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='productos_destacados_subtitulo',
        ),
        migrations.RemoveField(
            model_name='configuracionsitio',
            name='productos_destacados_titulo',
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mostrar_materiales_en_index',
            field=models.BooleanField(default=True, verbose_name='Mostrar materiales en Inicio'),
        ),
        migrations.AddField(
            model_name='configuracionsitio',
            name='mostrar_materiales_en_pagina',
            field=models.BooleanField(default=True, verbose_name='Mostrar materiales en página Materiales'),
        ),
        migrations.AlterField(
            model_name='cardpublica',
            name='es_paso_destacado',
            field=models.BooleanField(default=False, verbose_name='Paso destacado (verde)'),
        ),
        migrations.AlterField(
            model_name='cardpublica',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Recomendado: 400x300px', max_length=255, null=True, upload_to='cards/', verbose_name='Imagen del card'),
        ),
        migrations.AlterField(
            model_name='cardpublica',
            name='paso_numero',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Número del paso'),
        ),
        migrations.AlterField(
            model_name='cardpublica',
            name='seccion',
            field=models.CharField(choices=[('materiales', 'Materiales'), ('proceso', 'Pasos del Proceso')], max_length=20, verbose_name='Sección'),
        ),
    ]
