# Generated by Django 6.0.1 on 2026-03-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_configuracionsitio_cta_boton_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='instagram_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/ant_printer_3d/', max_length=500, null=True, verbose_name='Instagram'),
        ),
    ]
