# Generated by Django 6.0.1 on 2026-03-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_configuracionsitio_instagram_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionsitio',
            name='mostrar_boton_instagram',
            field=models.BooleanField(default=False, verbose_name='Mostrar botón flotante de Instagram'),
        ),
    ]
