# Generated by Django 6.0.1 on 2026-03-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_configuracionsitio_mostrar_boton_instagram'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionCalculadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio KG (RD$)')),
                ('precio_kwh', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio KWh (RD$)')),
                ('consumo_watts', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Consumo (Watts)')),
                ('vida_util_horas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Vida Útil Máquina (H)')),
                ('precio_repuestos', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Repuestos (RD$)')),
                ('margen_error_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Margen de Error')),
                ('multiplicador_ganancia', models.DecimalField(decimal_places=2, default=4, max_digits=5, verbose_name='Multiplicador de Ganancia')),
            ],
            options={
                'verbose_name': 'Configuración Calculadora',
                'verbose_name_plural': 'Configuración Calculadora',
            },
        ),
    ]
