# Generated by Django 6.0.1 on 2026-03-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_configuracioncalculadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='consumo_watts',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=10, verbose_name='Consumo (Watts)'),
        ),
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='margen_error_porcentaje',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='% Margen de Error'),
        ),
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='precio_kg',
            field=models.DecimalField(decimal_places=2, default=1600, max_digits=10, verbose_name='Precio KG (RD$)'),
        ),
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='precio_kwh',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=10, verbose_name='Precio KWh (RD$)'),
        ),
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='precio_repuestos',
            field=models.DecimalField(decimal_places=2, default=1650, max_digits=10, verbose_name='Precio Repuestos (RD$)'),
        ),
        migrations.AlterField(
            model_name='configuracioncalculadora',
            name='vida_util_horas',
            field=models.DecimalField(decimal_places=2, default=2779, max_digits=10, verbose_name='Vida Útil Máquina (H)'),
        ),
    ]
