# Generated by Django 6.0.1 on 2026-03-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_configuracioncalculadora_consumo_watts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Apex Nexus Technology', max_length=150, verbose_name='Nombre del Negocio')),
                ('slogan', models.CharField(blank=True, default='Tecnología a la medida de tus ideas.', max_length=200, verbose_name='Slogan / Subtítulo')),
                ('rnc', models.CharField(blank=True, default='', max_length=30, verbose_name='RNC / RIF')),
                ('telefono', models.CharField(blank=True, default='809-401-1729', max_length=30, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, default='info@ant.do', max_length=254, verbose_name='Email')),
                ('direccion', models.CharField(blank=True, default='Servicio a domicilio / Entrega acordada', max_length=250, verbose_name='Dirección')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='factura/', verbose_name='Logo (PNG/JPG recomendado 300×100 px)')),
                ('footer_texto', models.CharField(blank=True, default='Gracias por confiar en nosotros. Ante cualquier duda, contáctenos por WhatsApp.', max_length=300, verbose_name='Texto de pie de factura')),
                ('nota_legal', models.CharField(blank=True, default='Esta factura es un documento informativo. El pago confirma la aceptación del servicio.', max_length=400, verbose_name='Nota legal / condiciones')),
            ],
            options={
                'verbose_name': 'Configuración Factura',
                'verbose_name_plural': 'Configuración Factura',
            },
        ),
    ]
