# Generated by Django 6.0.1 on 2026-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Llamada', 'Llamada telefónica'), ('Email', 'Correo electrónico'), ('Reunion', 'Reunión presencial'), ('Nota', 'Nota interna')], max_length=20, verbose_name='Tipo de interacción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Historial de Cliente',
                'verbose_name_plural': 'Historial de Clientes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PerfilCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(blank=True, max_length=200, verbose_name='Empresa')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('codigo_postal', models.CharField(blank=True, max_length=10, verbose_name='Código Postal')),
                ('notas', models.TextField(blank=True, help_text='Notas internas sobre el cliente', verbose_name='Notas')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('recibir_notificaciones', models.BooleanField(default=True, verbose_name='Recibir notificaciones por email')),
            ],
            options={
                'verbose_name': 'Perfil de Cliente',
                'verbose_name_plural': 'Perfiles de Clientes',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
