# Generated by Django 6.0.1 on 2026-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto total')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto pagado')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Parcial', 'Pago parcial'), ('Cobrado', 'Cobrado'), ('Vencido', 'Vencido'), ('Incobrable', 'Incobrable')], default='Pendiente', max_length=15, verbose_name='Estado')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Cuenta por Cobrar',
                'verbose_name_plural': 'Cuentas por Cobrar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo', models.CharField(choices=[('Mantenimiento', 'Mantenimiento de equipo'), ('Energia', 'Energía eléctrica'), ('Compra_Material', 'Compra de material'), ('Herramientas', 'Herramientas y accesorios'), ('Servicios', 'Servicios (internet, teléfono, etc.)'), ('Otro', 'Otro')], max_length=20, verbose_name='Tipo de gasto')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('numero_factura', models.CharField(blank=True, max_length=100, verbose_name='Número de factura')),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='finanzas/comprobantes/', verbose_name='Comprobante')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('es_recurrente', models.BooleanField(default=False, help_text='¿Es un gasto mensual recurrente?', verbose_name='Gasto recurrente')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fuente', models.CharField(choices=[('Pedido', 'Pago de pedido'), ('Venta_Directa', 'Venta directa'), ('Servicio', 'Servicio adicional'), ('Otro', 'Otro')], default='Pedido', max_length=20, verbose_name='Fuente de ingreso')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.DateField(help_text='Primer día del mes', verbose_name='Mes')),
                ('tipo_gasto', models.CharField(choices=[('Mantenimiento', 'Mantenimiento de equipo'), ('Energia', 'Energía eléctrica'), ('Compra_Material', 'Compra de material'), ('Herramientas', 'Herramientas y accesorios'), ('Servicios', 'Servicios (internet, teléfono, etc.)'), ('Otro', 'Otro')], max_length=20, verbose_name='Tipo de gasto')),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto presupuestado')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Presupuesto Mensual',
                'verbose_name_plural': 'Presupuestos Mensuales',
                'ordering': ['-mes', 'tipo_gasto'],
            },
        ),
    ]
