# Generated by Django 6.0.1 on 2026-02-17 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finanzas', '0001_initial'),
        ('materiales', '0002_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='gasto',
            name='entrada_inventario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiales.entradainventario', verbose_name='Entrada de inventario'),
        ),
    ]
