# Generated by Django 6.0.1 on 2026-02-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_manual',
            field=models.BooleanField(default=False, verbose_name='Cliente manual (Sin login)'),
        ),
    ]
