# Generated by Django 6.0.1 on 2026-03-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email pendiente de verificación'),
        ),
    ]
