# Generated by Django 6.0.1 on 2026-02-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_ventas_dia', models.BooleanField(default=True)),
                ('mostrar_pedidos_pendientes', models.BooleanField(default=True)),
                ('mostrar_stock_bajo', models.BooleanField(default=True)),
                ('mostrar_ultimos_gastos', models.BooleanField(default=True)),
                ('mostrar_grafico_ventas', models.BooleanField(default=True)),
                ('periodo_grafico_ventas', models.CharField(choices=[('semana', 'Última semana'), ('mes', 'Último mes'), ('trimestre', 'Último trimestre')], default='mes', max_length=20, verbose_name='Período de gráfico de ventas')),
            ],
            options={
                'verbose_name': 'Configuración de Dashboard',
                'verbose_name_plural': 'Configuraciones de Dashboard',
            },
        ),
        migrations.CreateModel(
            name='ReporteGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del reporte')),
                ('tipo', models.CharField(choices=[('Ventas', 'Reporte de ventas'), ('Gastos', 'Reporte de gastos'), ('Inventario', 'Reporte de inventario'), ('Rentabilidad', 'Análisis de rentabilidad'), ('Pedidos', 'Reporte de pedidos')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('configuracion', models.JSONField(default=dict, help_text='Filtros y parámetros del reporte', verbose_name='Configuración')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('es_publico', models.BooleanField(default=False, help_text='¿Otros usuarios pueden ver este reporte?', verbose_name='Público')),
            ],
            options={
                'verbose_name': 'Reporte Guardado',
                'verbose_name_plural': 'Reportes Guardados',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
