# Generated by Django 6.0.1 on 2026-02-04 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('codigo_hex', models.CharField(blank=True, help_text='Código hexadecimal del color (ej: #FF0000)', max_length=7, verbose_name='Código Hex')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gramos_usados', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Gramos usados')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Consumo de Material',
                'verbose_name_plural': 'Consumos de Material',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_gramos', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad (gramos)')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Costo total')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de compra')),
                ('proveedor', models.CharField(blank=True, max_length=200, verbose_name='Proveedor')),
                ('numero_factura', models.CharField(blank=True, max_length=100, verbose_name='Número de factura')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('Entrada', 'Entrada'), ('Edición', 'Edición'), ('Eliminación', 'Eliminación'), ('Consumo', 'Consumo')], max_length=20, verbose_name='Acción')),
                ('cantidad_nueva', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cantidad nueva')),
                ('cantidad_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cantidad anterior')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Historial de Inventario',
                'verbose_name_plural': 'Historial de Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('pais_origen', models.CharField(blank=True, max_length=50, verbose_name='País de origen')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_por_gramo', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Costo por gramo')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Stock actual (gramos)')),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=100, help_text='Nivel de reorden', max_digits=12, verbose_name='Stock mínimo (gramos)')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para materiales descontinuados', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['tipo__nombre', 'marca__nombre', 'color__nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, help_text='Características y usos del material', verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Material',
                'verbose_name_plural': 'Tipos de Material',
                'ordering': ['nombre'],
            },
        ),
    ]
