# Generated by Django 6.0.1 on 2026-02-04 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materiales', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumomaterial',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido', verbose_name='Pedido'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='entrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiales.entradainventario', verbose_name='Entrada relacionada'),
        ),
        migrations.AddField(
            model_name='material',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.color', verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='material',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.marca', verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='historialinventario',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='entradainventario',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='consumomaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiales.material', verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='material',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materiales.tipomaterial', verbose_name='Tipo'),
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('tipo', 'marca', 'color')},
        ),
    ]
