# Generated by Django 6.0.1 on 2026-02-08 05:45

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_color_nombre_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='marca',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_marca_nombre_case_insensitive'),
        ),
        migrations.AddConstraint(
            model_name='tipomaterial',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('nombre'), name='unique_tipo_nombre_case_insensitive'),
        ),
    ]
