# Generated by Django 6.0.1 on 2026-02-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0003_color_unique_color_nombre_case_insensitive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='codigo_hex',
            field=models.CharField(blank=True, default='#10b981', help_text='Código hexadecimal del color (ej: #FF0000)', max_length=7, verbose_name='Código Hex'),
        ),
    ]
