# Generated by Django 6.0.1 on 2026-02-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiales', '0004_alter_color_codigo_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='enlace_compra',
            field=models.URLField(blank=True, help_text='Enlace a la tienda para reponer este material (ej: Keitron, Amazon, etc.)', max_length=500, null=True, verbose_name='Enlace de compra'),
        ),
    ]
